// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFZhxxvw06sykr1TwuQqNXfgKopKdNbg4',
    appId: '1:257196102688:web:eead387a4c1be6217d5845',
    messagingSenderId: '257196102688',
    projectId: 'ifchat-2fd12',
    authDomain: 'ifchat-2fd12.firebaseapp.com',
    storageBucket: 'ifchat-2fd12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx00w5wDdm-wHTxxUnaVGJnDJRJ5hqetw',
    appId: '1:257196102688:android:cb8d2d88e407c5b27d5845',
    messagingSenderId: '257196102688',
    projectId: 'ifchat-2fd12',
    storageBucket: 'ifchat-2fd12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-UdIyFAS2_gDVCLOAvOarEOfnKqv3HsU',
    appId: '1:257196102688:ios:7c0dcd0f09b8cb027d5845',
    messagingSenderId: '257196102688',
    projectId: 'ifchat-2fd12',
    storageBucket: 'ifchat-2fd12.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-UdIyFAS2_gDVCLOAvOarEOfnKqv3HsU',
    appId: '1:257196102688:ios:c4044957d0c769537d5845',
    messagingSenderId: '257196102688',
    projectId: 'ifchat-2fd12',
    storageBucket: 'ifchat-2fd12.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
